---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: nccl-networks
    resourceClaimTemplateName: nccl-interfaces
