apiVersion: resource.k8s.io/v1alpha3
kind:  ResourceClaim
metadata:
  name: nccl-networks-claim
spec:
  devices:
    requests:
    - name: net1
      deviceClassName: net1
    - name: net2
      deviceClassName: net2
    - name: net3
      deviceClassName: net3
    - name: net4
      deviceClassName: net4
    config:
    - opaque:
        driver: networking.k8s.io
        parameters:
          newName: "eth99"
          address: "192.168.2.2"
          mask: "255.255.255.0"
          mtu: "1500"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr1
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: nccl-networks
    resourceClaimName: nccl-networks-claim
